### PR TITLE
Inheritance by existent external type

### PR DESCRIPTION
**Pull request by leandroshan**
This will implement the use case of having an external module and type ex. "externalJSModule,Entity" that does not need to be created on .d.ts file, but it must extend some types in the current project.

C#
 [TypeScriptInterface(Name = "someEntity", ExistentExternalTypeName = "externalJSModule.Entity")]
    public class SomeEntity
    {
        public int Number { get; set; }
        public string Name { get; set; }
    }

.D.TS generated
declare module T4TS {
    export interface someEntity extends externalJSModule.Entity {
        Number: number;
        Name: string;
    }
}

// THIS ALREADY EXISTS SOMEWHERE IN THE APPLICATION 
// AND WILL NOT BE CREATED ON THE .D.TS FILES
declare module externalJSModule {
    interface Entity {
     
    }
}

This is very useful when using breezejs for example where all my client models will automatically be breeze client entities.

Please, let me know if you like it and/or if there is a better way of doing it or if this is already supported somehow and I didn't see it.

I have this working on my breeze project and it's great, I hope it can help others as well.

Thanks
Leandro

### CODE REVIEW

**Comment by cskeppstedt** [comment]
Hey, pretty cool idea. I would however suggest calling the property `Extends` instead of `ExistentExternalTypeName`, it makes it more clear what will actually happen. 

```c#
[TypeScriptInterface(Extends = "externalJSModule.Entity")]
public class SomeEntity
{
    public int Number { get; set; }
    public string Name { get; set; }
}
```

And in `InterfaceOutputAppender.cs` I would prefer to do something like this, making the `Extends` property a definite override over any inferred Parent of the interface.:

```c#
if (!string.IsNullOrEmpty(tsInterface.Extends))
{
    // use tsInterface.Extend
}
else if (tsInterface.Parent != null)
{
    // use Parent (as in current implementation)
}
```

What do you think about that?

**Comment by leandroshan** [comment]
I think it's great !!!
Do you want me to implement this way and do another PR? or you would do it in your end ?  let me know  ;-)

**Comment by leandroshan** [comment]
I'm sending you a new PR with these changes

**Comment by zeiphon** [comment]
Any progress on this PR? I actually came here with the intention to do exactly this.

**Comment by cskeppstedt** [comment]
Hey @leandroshan & @zeiphon. I've been away for a while, but I'm back now. I just merged this. I'm aiming to make a new release soon, I just need to take a look at the other issues/pr's first. Cheers!

**Comment by leandroshan** [comment]
Very nice !!!! congrats on the good job with this library, it helps a lot !

**Pull request merged**
